export const pages = {
    home: '/',
    login: '/login',
    shop: '/shop',
    register: '/register',
    addProduct: '/add-product',
    profile: '/profile',
    order: '/order',
    orderDetail: '/order-detail',
    product: '/product',
    productDetail: '/productDetail',
    cart: '/cart',
    password: '/password',
    user: '/user',
    announce: '/announce',
}